const sku = [
  {
    name: 'Саджанці Барбарис тунберга "Адмірейшн" 2 р.',
    id: 2301,
    locationId: 60,
    quantity: 146,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Барбарис тунберга "Атропурпуреа" 2 р.',
    id: 2296,
    locationId: 60,
    quantity: 196,
    pot: '2L',
  },
  {
    name: 'Саджанці Барбарис тунберга "Багатель" 2 р.',
    id: 2295,
    locationId: 60,
    quantity: 98,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Барбарис тунберга "Пінк Куїн" 2 р.',
    id: 4326,
    locationId: 60,
    quantity: 66,
    pot: '3L кв-кр',
  },
  {
    name: 'Барбарис тунберга "Ред Чіф" 2 р.',
    id: 4025,
    locationId: 60,
    quantity: 30,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Бересклет Форчуна "Емеральд Гаєті" 2 р.',
    id: 2304,
    locationId: 60,
    quantity: 33,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Бересклет Форчуна "Емеральд енд Голд" 2 р.',
    id: 2305,
    locationId: 60,
    quantity: 4,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Бересклет японський "Екстаз" 2 р.',
    id: 3311,
    locationId: 60,
    quantity: 24,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Бірючина звичайна "Лодензе" 2 р.',
    id: 2294,
    locationId: 62,
    quantity: 248,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Буддлея давида "Адоніс Блю" 2 р.',
    id: 2308,
    locationId: 62,
    quantity: 9,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Буддлея давида "Вайт Профьюжн" 2 р.',
    id: 3742,
    locationId: 62,
    quantity: 230,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Будлея давида "Роял Ред" 2 р.',
    id: 2991,
    locationId: 62,
    quantity: 237,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Бузина чорна "Блек Бьюті" 2 р.',
    id: 1323,
    locationId: 62,
    quantity: 22,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Бузок звичайний 1 р.',
    id: 3025,
    locationId: 61,
    quantity: 26,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Вейгела "Александра" 2 р.',
    id: 1327,
    locationId: 61,
    quantity: 25,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Вейгела "Брістоль Рубі" 2 р.',
    id: 3021,
    locationId: 62,
    quantity: 146,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Вейгела "Кандіда" 2 р.',
    id: 1328,
    locationId: 62,
    quantity: 13,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Вейгела "Нана Варієгата" 2 р.',
    id: 4029,
    locationId: 62,
    quantity: 208,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці верес Аллегретто',
    id: 4039,
    locationId: 60,
    quantity: 11,
    pot: '1L',
  },
  {
    name: 'Саджанці верес Кармен',
    id: 4043,
    locationId: 60,
    quantity: 30,
    pot: '1L',
  },
  {
    name: 'Саджанці верес Локі',
    id: 4045,
    locationId: 60,
    quantity: 25,
    pot: '1L',
  },
  {
    name: 'Саджанці Вівсяниця сиза',
    id: 2935,
    locationId: 60,
    quantity: 16,
    pot: '2L',
  },
  {
    name: 'Саджанці Гортензія волотиста "Ванілла Фрейз" 2 р.',
    id: 1333,
    locationId: 61,
    quantity: 47,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Вімс Ред" 2 р.',
    id: 3318,
    locationId: 61,
    quantity: 132,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Грандіфлора" 2 р.',
    id: 3319,
    locationId: 61,
    quantity: 27,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Конфетті" 2 р.',
    id: 1334,
    locationId: 61,
    quantity: 280,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Мега Мінді" 2 р.',
    id: 3320,
    locationId: 61,
    quantity: 110,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Меджикал Кендл" 2 р.',
    id: 3325,
    locationId: 61,
    quantity: 52,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Пінкі Вінкі" 2 р.',
    id: 3321,
    locationId: 61,
    quantity: 95,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Тардіва" 2 р.',
    id: 1336,
    locationId: 61,
    quantity: 4,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Юнік" 2 р.',
    id: 3322,
    locationId: 61,
    quantity: 151,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія деревовидна "Хілс оф Сноу" 2 р.',
    id: 3323,
    locationId: 61,
    quantity: 90,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія крупнолистна "Ендлес Самер Блум Стар" 2 р.',
    id: 2882,
    locationId: 61,
    quantity: 1,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дейція "Розеа Плена" 2 р.',
    id: 1337,
    locationId: 63,
    quantity: 496,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дейція "Турбілон Руж" 2 р.',
    id: 2285,
    locationId: 63,
    quantity: 9,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дейція гібридна "Монт Роуз" 2 р.',
    id: 1338,
    locationId: 63,
    quantity: 665,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дейція шорховата "Плена"',
    id: 1175,
    locationId: 62,
    quantity: 105,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дерен білий "Гоучалті" 2 р.',
    id: 2288,
    locationId: 62,
    quantity: 418,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дерен білий "Сібіріка" 2 р.',
    id: 1100,
    locationId: 62,
    quantity: 133,
    pot: '2L',
  },
  {
    name: 'Саджанці Жасмін гібридний "Лемоней" 2 р.',
    id: 3333,
    locationId: 62,
    quantity: 158,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Жимолость блискуча "Лемон Бьюті" 1 р.',
    id: 4350,
    locationId: 60,
    quantity: 446,
    pot: '1.5L',
  },
  {
    name: 'Саджанці Жимолость блискуча "Лемон Бьюті" 2 р.',
    id: 2293,
    locationId: 60,
    quantity: 67,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Жимолость глянцева "Елегант" 2 р.',
    id: 2293,
    locationId: 60,
    quantity: 315,
    pot: '2L',
  },
  {
    name: 'Саджанці Лаванда вузьколиста "Розеа" 2 р.',
    id: 1340,
    locationId: 61,
    quantity: 414,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Лаванда вузьколиста "Хідкот" 2 р.',
    id: 2287,
    locationId: 61,
    quantity: 45,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Лапчатка біла "Абботсвуд" 2 р.',
    id: 3342,
    locationId: 62,
    quantity: 115,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Лапчатка жовта  "Саттерс Голд" 2 р.',
    id: 4055,
    locationId: 62,
    quantity: 5,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Міскантус китайський "Граціелла" 2 р.',
    id: 2310,
    locationId: 60,
    quantity: 17,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Пенстемон "Дарк Тауерс" 2 р.',
    id: 3349,
    locationId: 61,
    quantity: 15,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Пієріс "Форест Флейм" 2 р.',
    id: 1343,
    locationId: 61,
    quantity: 47,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Пухироплідник калинолистний "Дартс Голд" 2 р.',
    id: 3354,
    locationId: 61,
    quantity: 163,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ракитник "Альбус" 2 р.',
    id: 3357,
    locationId: 61,
    quantity: 18,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея японська "Меджик Карпет" 2 р.',
    id: 4057,
    locationId: 63,
    quantity: 73,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея вангутта  "Голд Фонтан" 2 р.',
    id: 3362,
    locationId: 63,
    quantity: 210,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея ніппонська "Вайт Карпет" 2 р.',
    id: 3364,
    locationId: 63,
    quantity: 134,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея японська "Голден Прінцес" 2 р.',
    id: 2688,
    locationId: 63,
    quantity: 287,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея японська "Голдфлейм" 2 р.',
    id: 2283,
    locationId: 63,
    quantity: 82,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея японська "Літл Прінцес" 2 р.',
    id: 1097,
    locationId: 63,
    quantity: 105,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея японська "Фробеллі" 2 р.',
    id: 3026,
    locationId: 63,
    quantity: 60,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Форзиція середньоросла "Варієгата" 2 р.',
    id: 4337,
    locationId: 62,
    quantity: 36,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Форзиція середньоросла "Марі Діор" 2 р.',
    id: 3365,
    locationId: 62,
    quantity: 82,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Форзиція середньоросла "Мініголд" 2 р.',
    id: 1349,
    locationId: 62,
    quantity: 8,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці абрикоса Київський Красень 1 р.',
    id: 1118,
    locationId: 53,
    quantity: 66,
    pot: '7.5L',
  },
  {
    name: 'Саджанці абрикоса Мелітопольський Ранній 1 р.',
    id: 2671,
    locationId: 54,
    quantity: 80,
    pot: '7.5L',
  },
  {
    name: 'Саджанці абрикоса Мелітопольський Чорний 1 р.',
    id: 4328,
    locationId: 54,
    quantity: 16,
    pot: '7.5L',
  },
  {
    name: 'Саджанці абрикоса Робада 1 р.',
    id: 3368,
    locationId: 53,
    quantity: 31,
    pot: '7.5L',
  },
  {
    name: 'Саджанці абрикоса Рубіста 1 р.',
    id: 3369,
    locationId: 53,
    quantity: 11,
    pot: '7.5L',
  },
  {
    name: 'Саджанці абрикоса Фарбелі 1 р.',
    id: 1693,
    locationId: 53,
    quantity: 9,
    pot: '7.5L',
  },
  {
    name: 'Саджанці абрикоса Цунамі 1 р.',
    id: 3370,
    locationId: 53,
    quantity: 79,
    pot: '7.5L',
  },
  {
    name: 'Саджанці абрикоса Чорний Принц 1 р.',
    id: 2607,
    locationId: 53,
    quantity: 70,
    pot: '7.5L',
  },
  {
    name: 'Саджанці вишні Богуславка',
    id: 4141,
    locationId: 48,
    quantity: 108,
    pot: '7.5L',
  },
  {
    name: 'Саджанці вишні Ерді Крупноплідна 1 р.',
    id: 2623,
    locationId: 48,
    quantity: 60,
    pot: '7.5L',
  },
  {
    name: 'Саджанці вишні Чудо Вишня 1 р.',
    id: 4140,
    locationId: 54,
    quantity: 24,
    pot: '7.5L',
  },
  {
    name: 'Саджанці груші Вересневе Дево 1 р.',
    id: 4138,
    locationId: 55,
    quantity: 103,
    pot: '7.5L',
  },
  {
    name: 'Саджанці груші Конференція 1 р.',
    id: 3372,
    locationId: 55,
    quantity: 109,
    pot: '7.5L',
  },
  {
    name: 'Саджанці груші Ніколай Крюгер 1 р.',
    id: 3375,
    locationId: 55,
    quantity: 68,
    pot: '7.5L',
  },
  {
    name: 'Саджанці груші Ноябрська 1 р.',
    id: 1792,
    locationId: 55,
    quantity: 62,
    pot: '7.5L',
  },
  {
    name: 'Саджанці нектарина інжирного Донат 1 р.',
    id: 4145,
    locationId: 54,
    quantity: 118,
    pot: '7.5L',
  },
  {
    name: 'Саджанці нектарина Ред Робін 1 р.',
    id: 4146,
    locationId: 53,
    quantity: 96,
    pot: '7.5L',
  },
  {
    name: 'Саджанці нектарина Супер Куїн',
    id: 4369,
    locationId: 54,
    quantity: 5,
    pot: '7.5L',
  },
  {
    name: 'Саджанці нектарина Фантазія 1 р.',
    id: 4273,
    locationId: 54,
    quantity: 12,
    pot: '12L',
  },
  {
    name: 'Саджанці нектарина Фантазія 1 р.',
    id: 2628,
    locationId: 53,
    quantity: 29,
    pot: '7.5L',
  },
  {
    name: 'Саджанці нектарина Харблейз 1 р.',
    id: 1811,
    locationId: 53,
    quantity: 55,
    pot: '7.5L',
  },
  {
    name: 'Саджанці персика інжирного Сатурн 1 р.',
    id: 4144,
    locationId: 54,
    quantity: 64,
    pot: '7.5L',
  },
  {
    name: 'Саджанці персика Канадіан Хармоні 1 р.',
    id: 4275,
    locationId: 54,
    quantity: 62,
    pot: '12L',
  },
  {
    name: 'Саджанці персика Канадіан Хармоні 1 р.',
    id: 4370,
    locationId: 54,
    quantity: 2,
    pot: '7.5L',
  },
  {
    name: 'Саджанці персика Мостиський 1р.',
    id: 3379,
    locationId: 54,
    quantity: 28,
    pot: '7.5L',
  },
  {
    name: 'Саджанці персика Рубіновий Принц 1р.',
    id: 3378,
    locationId: 54,
    quantity: 105,
    pot: '7.5L',
  },
  {
    name: 'Саджанці персика Санкрест 1 р.',
    id: 4276,
    locationId: 54,
    quantity: 7,
    pot: '12L',
  },
  {
    name: 'Саджанці персика "Флемінг Фюрі" 1 р.',
    id: 2608,
    locationId: 54,
    quantity: 68,
    pot: '7.5L',
  },
  {
    name: 'Саджанці персика Харнас 1р.',
    id: 4234,
    locationId: 55,
    quantity: 135,
    pot: '7.5L',
  },
  {
    name: 'Саджанці сливи Блю Фрі 1 р.',
    id: 1108,
    locationId: 52,
    quantity: 31,
    pot: '7.5L',
  },
  {
    name: 'Саджанці сливи Кабардинська Рання 1 р.',
    id: 3382,
    locationId: 52,
    quantity: 22,
    pot: '7.5L',
  },
  {
    name: 'Саджанці сливи Кишинівська 2 р.',
    id: 4278,
    locationId: 52,
    quantity: 7,
    pot: '7.5L',
  },
  {
    name: 'Саджанці сливи Оцарк Премєр 2 р.',
    id: 1109,
    locationId: 52,
    quantity: 22,
    pot: '7.5L',
  },
  {
    name: 'Саджанці черешні Дачниця 1 р.',
    id: 4142,
    locationId: 49,
    quantity: 124,
    pot: '7.5L',
  },
  {
    name: 'Саджанці черешні Канадіан Гігант 1 р.',
    id: 4324,
    locationId: 48,
    quantity: 19,
    pot: '7.5L',
  },
  {
    name: 'Саджанці черешні Крупноплідна 2 р.',
    id: 2964,
    locationId: 48,
    quantity: 66,
    pot: '7.5L',
  },
  {
    name: 'Саджанці черешні Лапінс 1 р.',
    id: 4230,
    locationId: 49,
    quantity: 123,
    pot: '7.5L',
  },
  {
    name: 'Саджанці черешні Рубінова Рання 1 р.',
    id: 4143,
    locationId: 49,
    quantity: 114,
    pot: '7.5L',
  },
  {
    name: 'Саджанці черешні Самміт 1 р.',
    id: 4325,
    locationId: 48,
    quantity: 44,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Вільямс Прайд 1 р.',
    id: 3389,
    locationId: 50,
    quantity: 230,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Віста Белла 2 р.',
    id: 4373,
    locationId: 51,
    quantity: 138,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Гренні Сміт 1 р.',
    id: 4374,
    locationId: 50,
    quantity: 16,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Джеромін 2 р.',
    id: 2949,
    locationId: 50,
    quantity: 43,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Конфєтне 1 р.',
    id: 1684,
    locationId: 50,
    quantity: 42,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Луна 1 р.',
    id: 4331,
    locationId: 49,
    quantity: 143,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Пінова  2 р.',
    id: 2974,
    locationId: 50,
    quantity: 29,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Прима 2 р.',
    id: 4282,
    locationId: 49,
    quantity: 53,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Ренет Симиренко 1 р.',
    id: 4136,
    locationId: 51,
    quantity: 191,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Розелла 1 р.',
    id: 2615,
    locationId: 50,
    quantity: 62,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Слава Переможцям 1 р.',
    id: 1685,
    locationId: 50,
    quantity: 18,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Флоріна 2 р.',
    id: 2979,
    locationId: 49,
    quantity: 89,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Фуджі 1 р.',
    id: 2610,
    locationId: 51,
    quantity: 202,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Чемпіон 2 р.',
    id: 2954,
    locationId: 51,
    quantity: 120,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Боніка 90',
    id: 1125,
    locationId: 44,
    quantity: 10,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Дам де Кьор 90',
    id: 1802,
    locationId: 44,
    quantity: 4,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Джулія Чайльд 90',
    id: 4301,
    locationId: 44,
    quantity: 2,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Кімоно 90',
    id: 1735,
    locationId: 44,
    quantity: 39,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Кроненбург 90',
    id: 1169,
    locationId: 44,
    quantity: 39,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Куїн Елізабет 90',
    id: 1133,
    locationId: 44,
    quantity: 9,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Ола 90',
    id: 4306,
    locationId: 44,
    quantity: 40,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Паскалі 90',
    id: 1803,
    locationId: 44,
    quantity: 10,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Пікаділлі 90',
    id: 3006,
    locationId: 44,
    quantity: 1,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Піс (Глорія Дей) 90',
    id: 4308,
    locationId: 44,
    quantity: 14,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Самба 90',
    id: 4313,
    locationId: 44,
    quantity: 6,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Санблест (Ландора) 90',
    id: 4307,
    locationId: 44,
    quantity: 3,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Сільвер Стар 90',
    id: 3008,
    locationId: 44,
    quantity: 45,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Скарлетта 90',
    id: 4309,
    locationId: 44,
    quantity: 17,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Сноу Баллет 90',
    id: 4310,
    locationId: 44,
    quantity: 6,
    pot: '7.5L',
  },
  {
    name: 'Саджанці троянд на штамбі Шейла Парфум 90',
    id: 4311,
    locationId: 44,
    quantity: 41,
    pot: '7.5L',
  },
  {
    name: 'Саджанці брусниці Корал 1 р.',
    id: 1093,
    locationId: 69,
    quantity: 440,
    pot: '1.5L',
  },
  {
    name: 'Саджанці брусниці Корал 2 р.',
    id: 2945,
    locationId: 69,
    quantity: 159,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці брусниці Руно Белявське 1 р.',
    id: 4283,
    locationId: 69,
    quantity: 155,
    pot: '1.5L',
  },
  {
    name: 'Саджанці брусниці Руно Белявське 2 р.',
    id: 1085,
    locationId: 69,
    quantity: 53,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Годжі Корнан Біг 1 р.',
    id: 4130,
    locationId: 70,
    quantity: 173,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці жимолості Алісія 1 р.',
    id: 4100,
    locationId: 69,
    quantity: 834,
    pot: '1L',
  },
  {
    name: 'Саджанці жимолості Бакчарська Ювілейна 1 р.',
    id: 4101,
    locationId: 69,
    quantity: 42,
    pot: '1L',
  },
  {
    name: 'Саджанці жимолості  Аврора',
    id: 41011,
    locationId: 69,
    quantity: 276,
    pot: '1L',
  },
  {
    name: 'Саджанці журавлини Бергман  1 р.',
    id: 4202,
    locationId: 69,
    quantity: 134,
    pot: '1.5L',
  },
  {
    name: 'Саджанці Лимонника китайського 2 р.',
    id: 2680,
    locationId: 70,
    quantity: 385,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці троянд Голден Гейт',
    id: 1078,
    locationId: 34,
    quantity: 209,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Жасміна',
    id: 1075,
    locationId: 34,
    quantity: 172,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Жасміна',
    id: 1075,
    locationId: 33,
    quantity: 50,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Жасміна',
    id: 1075,
    locationId: 33,
    quantity: 60,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Кіс мі Кейт',
    id: 1718,
    locationId: 43,
    quantity: 210,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Лагуна',
    id: 17181,
    locationId: 43,
    quantity: 158,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Лагуна',
    id: 17181,
    locationId: 34,
    quantity: 77,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Августа Луїза',
    id: 17181,
    locationId: 34,
    quantity: 818,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Алоха',
    id: 1081,
    locationId: 42,
    quantity: 160,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Алоха',
    id: 1081,
    locationId: 33,
    quantity: 50,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Алоха',
    id: 1081,
    locationId: 33,
    quantity: 60,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Вандерфул Ворд',
    id: 3399,
    locationId: 42,
    quantity: 120,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Хот Чоколейт',
    id: 3397,
    locationId: 42,
    quantity: 114,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Фо Ю Айс Онлі',
    id: 1722,
    locationId: 42,
    quantity: 59,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Фо Ю Айс Онлі',
    id: 1722,
    locationId: 33,
    quantity: 120,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Аннапурна',
    id: 2258,
    locationId: 42,
    quantity: 410,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Блек Баккара',
    id: 3408,
    locationId: 42,
    quantity: 339,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Черрі Леді',
    id: 1714,
    locationId: 42,
    quantity: 371,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Ленка Фрайла',
    id: 3396,
    locationId: 42,
    quantity: 120,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Веддінг Беллз',
    id: 1709,
    locationId: 42,
    quantity: 120,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Веддінг Беллз',
    id: 1709,
    locationId: 33,
    quantity: 109,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Лайонс Роуз',
    id: 1076,
    locationId: 42,
    quantity: 260,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Віолет Парфум',
    id: 3410,
    locationId: 42,
    quantity: 272,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Папіллон',
    id: 4067,
    locationId: 42,
    quantity: 411,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Версилія',
    id: 3409,
    locationId: 41,
    quantity: 218,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Версилія',
    id: 3409,
    locationId: 32,
    quantity: 122,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Аспірин',
    id: 4061,
    locationId: 41,
    quantity: 259,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Казіно',
    id: 3399,
    locationId: 47,
    quantity: 110,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Шнівальцер',
    id: 4064,
    locationId: 47,
    quantity: 111,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Мусімара',
    id: 33991,
    locationId: 47,
    quantity: 120,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Джинджер Сілабаб',
    id: 1703,
    locationId: 47,
    quantity: 150,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Чаплінз Пінк',
    id: 1703,
    locationId: 33,
    quantity: 70,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці троянд Хендель',
    id: 1703,
    locationId: 33,
    quantity: 68,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці троянд Пінк Мусімара',
    id: 4063,
    locationId: 47,
    quantity: 90,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Пінк Мусімара',
    id: 4063,
    locationId: 33,
    quantity: 65,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці троянд Іден Роуз',
    id: 33994,
    locationId: 47,
    quantity: 207,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці троянд Гранд Аморе',
    id: 1717,
    locationId: 43,
    quantity: 120,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Гранд Аморе',
    id: 1717,
    locationId: 37,
    quantity: 113,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Клер Маршал',
    id: 1759,
    locationId: 43,
    quantity: 170,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Дуфтвольке',
    id: 1759,
    locationId: 37,
    quantity: 132,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Горджес',
    id: 3405,
    locationId: 43,
    quantity: 260,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Сувенір де Баден-Баден',
    id: 1077,
    locationId: 43,
    quantity: 211,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Сувенір де Баден-Баден',
    id: 1077,
    locationId: 36,
    quantity: 478,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Бельвью',
    id: 1707,
    locationId: 43,
    quantity: 228,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Бельвью',
    id: 1707,
    locationId: 37,
    quantity: 1142,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Графиня Діана',
    id: 1717,
    locationId: 43,
    quantity: 281,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Світхарт',
    id: 2254,
    locationId: 41,
    quantity: 161,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Блек Меджик',
    id: 2254,
    locationId: 34,
    quantity: 506,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Світ Лав',
    id: 22542,
    locationId: 41,
    quantity: 160,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Джулія Чайльд',
    id: 3393,
    locationId: 41,
    quantity: 261,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Хайдетраум',
    id: 3414,
    locationId: 41,
    quantity: 259,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Хайдетраум',
    id: 3414,
    locationId: 34,
    quantity: 89,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Куїн оф Хертс',
    id: 1080,
    locationId: 41,
    quantity: 214,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Куїн оф Хертс',
    id: 1080,
    locationId: 36,
    quantity: 135,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Софі Лорен',
    id: 4126,
    locationId: 41,
    quantity: 158,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Мерхензаубер',
    id: 1711,
    locationId: 41,
    quantity: 109,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Мерхензаубер',
    id: 1711,
    locationId: 36,
    quantity: 320,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Герцогиня Крістіана',
    id: 1083,
    locationId: 40,
    quantity: 259,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Глоріус Бебілон Айс',
    id: 4318,
    locationId: 40,
    quantity: 60,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Глоріус Бебілон Айс',
    id: 4318,
    locationId: 33,
    quantity: 168,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Блашинг Бебілон Айс',
    id: 4318,
    locationId: 33,
    quantity: 120,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Оранжері',
    id: 10799,
    locationId: 40,
    quantity: 260,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Оранжері',
    id: 10799,
    locationId: 33,
    quantity: 110,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Бенгалі',
    id: 10794,
    locationId: 40,
    quantity: 281,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Сіа Фом',
    id: 1704,
    locationId: 40,
    quantity: 269,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Сіа Фом',
    id: 1704,
    locationId: 32,
    quantity: 111,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Ніна Вейбул',
    id: 2685,
    locationId: 40,
    quantity: 240,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Вестерленд',
    id: 3409,
    locationId: 40,
    quantity: 119,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Ель Торо',
    id: 3411,
    locationId: 47,
    quantity: 255,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Лемон Ваза',
    id: 3395,
    locationId: 47,
    quantity: 121,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Артур Белл',
    id: 3547,
    locationId: 47,
    quantity: 220,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Розаріум Уетерзен',
    id: 1721,
    locationId: 47,
    quantity: 213,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Фаєрбьорд',
    id: 1713,
    locationId: 47,
    quantity: 160,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Фаєрбьорд',
    id: 1713,
    locationId: 33,
    quantity: 129,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Роткепчен',
    id: 1804,
    locationId: 46,
    quantity: 120,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Роткепчен',
    id: 1804,
    locationId: 33,
    quantity: 68,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Тренді Бебілон Айс',
    id: 4319,
    locationId: 46,
    quantity: 62,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Тренді Бебілон Айс',
    id: 4319,
    locationId: 33,
    quantity: 120,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Бордо',
    id: 1708,
    locationId: 46,
    quantity: 111,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Бордо',
    id: 1708,
    locationId: 33,
    quantity: 55,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Френдшип',
    id: 3412,
    locationId: 46,
    quantity: 120,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Верано',
    id: 3404,
    locationId: 46,
    quantity: 212,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Беверлі',
    id: 1706,
    locationId: 46,
    quantity: 261,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Беверлі',
    id: 1706,
    locationId: 33,
    quantity: 129,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Єллоу Мейлав',
    id: 3394,
    locationId: 40,
    quantity: 259,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Помпонелла',
    id: 1079,
    locationId: 40,
    quantity: 299,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Розенфешінейшн',
    id: 1079,
    locationId: 37,
    quantity: 580,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Помпонелла',
    id: 1079,
    locationId: 32,
    quantity: 237,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Александра Принцеса Люксембурга',
    id: 10793,
    locationId: 41,
    quantity: 259,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Сава Река',
    id: 3415,
    locationId: 40,
    quantity: 259,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Новаліс',
    id: 1079,
    locationId: 46,
    quantity: 298,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Новаліс',
    id: 1079,
    locationId: 34,
    quantity: 66,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Коко Локо',
    id: 34113,
    locationId: 46,
    quantity: 160,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Карен Бліксен',
    id: 34117,
    locationId: 46,
    quantity: 217,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Апрікола',
    id: 1716,
    locationId: 46,
    quantity: 217,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Апрікола',
    id: 1716,
    locationId: 33,
    quantity: 64,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Крем Ебанденс',
    id: 17166,
    locationId: 46,
    quantity: 133,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Люстіге',
    id: 17166,
    locationId: 37,
    quantity: 72,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Маджестік',
    id: 17166,
    locationId: 33,
    quantity: 68,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Кларет Піксі',
    id: 1748,
    locationId: 46,
    quantity: 269,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Скарлет Мейландекор',
    id: 1705,
    locationId: 45,
    quantity: 199,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Скарлет Мейландекор',
    id: 1705,
    locationId: 32,
    quantity: 74,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Лімона',
    id: 1710,
    locationId: 45,
    quantity: 230,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Лімона',
    id: 1710,
    locationId: 34,
    quantity: 59,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Гебрюдер Грім',
    id: 1083,
    locationId: 45,
    quantity: 259,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Гебрюдер Грім',
    id: 1083,
    locationId: 37,
    quantity: 472,
    pot: '3L трояндовий',
  },
  {
    name: 'Cаджанці троянд Пінк Піс',
    id: 4067,
    locationId: 45,
    quantity: 260,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Ред Іден Роуз',
    id: 1720,
    locationId: 45,
    quantity: 209,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Ред Іден Роуз',
    id: 1720,
    locationId: 37,
    quantity: 172,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Ред Інтуїшн',
    id: 1720,
    locationId: 36,
    quantity: 1010,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Фенсі Бебілон Айс',
    id: 4320,
    locationId: 45,
    quantity: 79,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Майн Мюнхен',
    id: 1731,
    locationId: 45,
    quantity: 250,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Бранд Піксі',
    id: 1723,
    locationId: 45,
    quantity: 262,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці троянд Ротілія',
    id: 1805,
    locationId: 45,
    quantity: 105,
    pot: '3L трояндовий',
  },
  {
    name: 'Саджанці Барбарис тунберга "Дартс Ред Леді" 2 р.',
    id: 180535,
    locationId: 64,
    quantity: 300,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Барбарис тунберга "Оранж Рокет" 1 р.',
    id: 3854,
    locationId: 65,
    quantity: 63,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Барбарис тунберга "Самме Чоколат" 2 р.',
    id: 38547,
    locationId: 64,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Барбарис тунберга "Хот Чоколат" 2 р.',
    id: 3063,
    locationId: 64,
    quantity: 300,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Буддлея давида "Адоніс Блю" 1 р.',
    id: 3063,
    locationId: 65,
    quantity: 152,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Бузина чорна "Блек Бьюті" 1р.',
    id: 306321,
    locationId: 65,
    quantity: 48,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Вейгела "Александра" 1 р.',
    id: 306321,
    locationId: 65,
    quantity: 213,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Вейгела "Кандіда" 1 р.',
    id: 1818,
    locationId: 65,
    quantity: 47,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гібіскус сирійський "Блю Шифон" 1р.',
    id: 3858,
    locationId: 65,
    quantity: 17,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Ваніла Фрейз" 1 р.',
    id: 1821,
    locationId: 64,
    quantity: 297,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Вімс Ред" 1 р.',
    id: 302856,
    locationId: 64,
    quantity: 232,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Грандіфлора" 1 р.',
    id: 30334,
    locationId: 64,
    quantity: 49,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Конфетті" 1 р.',
    id: 1776,
    locationId: 64,
    quantity: 166,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Мега Мінді" 1 р.',
    id: 3031,
    locationId: 64,
    quantity: 190,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Меджикал Кендл" 1 р.',
    id: 3031,
    locationId: 64,
    quantity: 40,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Полар Бер" 1 р.',
    id: 3326,
    locationId: 65,
    quantity: 57,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Тардіва" 1 р.',
    id: 1822,
    locationId: 64,
    quantity: 211,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Юнік" 1 р.',
    id: 3030,
    locationId: 64,
    quantity: 233,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія деревовидна "Хілс оф Сноу" 1 р.',
    id: 3032,
    locationId: 64,
    quantity: 249,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дейція "Турбілон Руж" 1 р.',
    id: 3037,
    locationId: 65,
    quantity: 69,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дерен білий "Гоучалті" 1 р.',
    id: 3331,
    locationId: 65,
    quantity: 74,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Дерен білий "Сібіріка" 1 р.',
    id: 4358,
    locationId: 65,
    quantity: 18,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Лаванда вузьколиста "Дварф Блю" 1 р.',
    id: 3027,
    locationId: 66,
    quantity: 492,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Лапчатка рожева "Пінк Куїн" 1 р.',
    id: 4356,
    locationId: 66,
    quantity: 236,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Пухироплідник калинолистний "Дартс Голд" 1 р.',
    id: 3035,
    locationId: 67,
    quantity: 602,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Пухироплідник калинолистний "Діаболо" 1 р.',
    id: 1769,
    locationId: 66,
    quantity: 272,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Пухироплідник калинолистний "Леді ін Ред" 1 р.',
    id: 3034,
    locationId: 67,
    quantity: 502,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Рододендрон Елегантс 2 р.',
    id: 4247,
    locationId: 59,
    quantity: 50,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Рододендрон Кальсап 2 р.',
    id: 42478,
    locationId: 59,
    quantity: 244,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Рододендрон Нова Зембла 2 р.',
    id: 42487,
    locationId: 59,
    quantity: 250,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Лаванда вузьколиста "Розеа" 1 р.',
    id: 1768,
    locationId: 66,
    quantity: 1044,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея японська "Літл Прінцес" 2 р.',
    id: 1097,
    locationId: 67,
    quantity: 511,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Форзиція середньоросла "Марі Діор" 1 р.',
    id: 30362,
    locationId: 65,
    quantity: 687,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Форзиція середньоросла "Мініголд" 1 р.',
    id: 1771,
    locationId: 65,
    quantity: 420,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Хоста "Сем енд Сабстенс" 2р.',
    id: 177381,
    locationId: 65,
    quantity: 100,
    pot: '1.5L кр',
  },
  {
    name: 'Саджанці Хоста "Вайд Брім" 2р.',
    id: 173381,
    locationId: 65,
    quantity: 200,
    pot: '1.5L кр',
  },
  {
    name: 'Саджанці Хоста "Френсіс Вільям" 2р.',
    id: 173380,
    locationId: 65,
    quantity: 200,
    pot: '1.5L кр',
  },
  {
    name: 'Саджанці абрикоса Цунамі 1 р.',
    id: 33706,
    locationId: 57,
    quantity: 100,
    pot: '7.5L',
  },
  {
    name: 'Саджанці вишні Ерді Крупноплідна 1 р.',
    id: 41417,
    locationId: 58,
    quantity: 50,
    pot: '7.5L',
  },
  {
    name: 'Саджанці вишні Ерді Ботермо 1 р.',
    id: 2956,
    locationId: 58,
    quantity: 110,
    pot: '7.5L',
  },
  {
    name: 'Саджанці груші Бере Київська 1 р.',
    id: 4268,
    locationId: 58,
    quantity: 206,
    pot: '7.5L',
  },
  {
    name: 'Саджанці груші Вільямс Літня 1 р.',
    id: 4220,
    locationId: 57,
    quantity: 200,
    pot: '7.5L',
  },
  {
    name: 'Саджанці груші Ноябрська 1 р.',
    id: 17921,
    locationId: 57,
    quantity: 100,
    pot: '7.5L',
  },
  {
    name: 'Саджанці груші Талгарська Красуня 1 р.',
    id: 1687,
    locationId: 57,
    quantity: 106,
    pot: '7.5L',
  },
  {
    name: 'Саджанці сливи Блю Фрі 1 р.',
    id: 16872,
    locationId: 57,
    quantity: 55,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Барселонський 2 р.',
    id: 1751,
    locationId: 52,
    quantity: 47,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Варшавський 2 р.',
    id: 2674,
    locationId: 52,
    quantity: 20,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Вебба Цінний 2 р.',
    id: 1696,
    locationId: 52,
    quantity: 13,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Галлє 2 р.',
    id: 2630,
    locationId: 52,
    quantity: 144,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Каталонський 2 р.',
    id: 2675,
    locationId: 52,
    quantity: 12,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Сирена 2 р.',
    id: 1112,
    locationId: 56,
    quantity: 51,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Трапезундський 2  р.',
    id: 4235,
    locationId: 52,
    quantity: 92,
    pot: '7.5L',
  },
  {
    name: 'Саджанці сливи Оцарк Премєр 1 р.',
    id: 11097,
    locationId: 57,
    quantity: 99,
    pot: '7.5L',
  },
  {
    name: 'Саджанці черешні Ніжність 1 р.',
    id: 2964,
    locationId: 56,
    quantity: 102,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Голден Делішес 1р.',
    id: 4212,
    locationId: 56,
    quantity: 99,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Джонаголд  1 р.',
    id: 4213,
    locationId: 56,
    quantity: 100,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Ред Чіф 1 р.',
    id: 2975,
    locationId: 56,
    quantity: 100,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Ренет Симиренко 1 р.',
    id: 4214,
    locationId: 56,
    quantity: 102,
    pot: '7.5L',
  },
  {
    name: 'Саджанці яблуні Чемпіон 1 р.',
    id: 2928,
    locationId: 56,
    quantity: 200,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Косфорд 2 р.',
    id: 16951,
    locationId: 52,
    quantity: 100,
    pot: '7.5L',
  },
  {
    name: 'Саджанці фундука Косфорд 2 р.',
    id: 16952,
    locationId: 56,
    quantity: 63,
    pot: '7.5L',
  },
  {
    name: 'Саджанці Спірея сіра "Грефшейм" 1 р.',
    id: 3856,
    locationId: 67,
    quantity: 150,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Тис середній Стефанія',
    id: 3741,
    locationId: 72,
    quantity: 45,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Анніек"',
    id: 3065,
    locationId: 74,
    quantity: 150,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Брабант"',
    id: 2848,
    locationId: 72,
    quantity: 9,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Голден Даніка"',
    id: 4250,
    locationId: 72,
    quantity: 80,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Глобоза Ауреа"',
    id: 42505,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Голден Глоуб"',
    id: 42506,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Грін Баббл"',
    id: 4340,
    locationId: 72,
    quantity: 95,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Даніка Ауреа"',
    id: 4339,
    locationId: 73,
    quantity: 2,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Даніка"',
    id: 3424,
    locationId: 73,
    quantity: 140,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Даніка"',
    id: 3425,
    locationId: 75,
    quantity: 150,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Літтл Джем"',
    id: 3418,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Місс Фрості"',
    id: 341865,
    locationId: 75,
    quantity: 50,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Смарагд"',
    id: 2942,
    locationId: 73,
    quantity: 2,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Смарагд"',
    id: 3859,
    locationId: 74,
    quantity: 1473,
    pot: '2L кр',
  },
  {
    name: 'Саджанці Туя західна "Смарагд Варігатта"',
    id: 3418,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Смарагд" 40 см',
    id: 3845,
    locationId: 73,
    quantity: 389,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Спотті Смарагд"',
    id: 3868,
    locationId: 74,
    quantity: 405,
    pot: '2L кр',
  },
  {
    name: 'Саджанці Туя західна "Спотті Смарагд" 30 см',
    id: 4360,
    locationId: 73,
    quantity: 5,
    pot: '3L кв-кр',
  },
  {
    name: ' Саджанці Туя західна "Тедді"',
    id: 3067,
    locationId: 72,
    quantity: 15,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Тедді"',
    id: 30672,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Янтар"',
    id: 4342,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя західна "Янтар"',
    id: 434244,
    locationId: 72,
    quantity: 200,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя східна "Ауреа Нана"',
    id: 2845,
    locationId: 73,
    quantity: 4,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Туя східна "Моргані"',
    id: 4252,
    locationId: 73,
    quantity: 27,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець віргінський "Блю Клауд"',
    id: 3436,
    locationId: 73,
    quantity: 5,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець віргінський "Голден Спрінг"',
    id: 3042,
    locationId: 73,
    quantity: 4,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець віргінський "Грей Оул"',
    id: 3434,
    locationId: 73,
    quantity: 3,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець горизонтальний "Альпіна"',
    id: 3439,
    locationId: 72,
    quantity: 131,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець горизонтальний "Блю Чіп"',
    id: 3447,
    locationId: 72,
    quantity: 86,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець горизонтальний "Лайм Глоу"',
    id: 4255,
    locationId: 72,
    quantity: 260,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець звичайний "Голд Кон"',
    id: 3430,
    locationId: 72,
    quantity: 42,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець козацький "Блю Дануб"',
    id: 3449,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець китайський "Експанса Варієгата"',
    id: 34493,
    locationId: 72,
    quantity: 4,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець китайський "Сан Хосе"',
    id: 2884,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець китайський "Стрікта"',
    id: 288478,
    locationId: 72,
    quantity: 54,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець лускатий "Блю Карпет"',
    id: 2850,
    locationId: 72,
    quantity: 97,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець лускатий "Блю Карпет"',
    id: 3437,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець лускатий "Блю Спайдер"',
    id: 343766,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець лускатий "Вілсоні"',
    id: 2893,
    locationId: 73,
    quantity: 33,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець лускатий "Холгер"',
    id: 4345,
    locationId: 72,
    quantity: 65,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець прибережний "Олл Голд"',
    id: 3432,
    locationId: 72,
    quantity: 29,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець середній "Ауреа"',
    id: 4347,
    locationId: 72,
    quantity: 67,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець середній "Кінг оф Спрінг"',
    id: 4346,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець середній "Голд Стар"',
    id: 4257,
    locationId: 72,
    quantity: 58,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець середній "Шерідан Голд"',
    id: 3445,
    locationId: 72,
    quantity: 55,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець скальний "Блю Ерроу',
    id: 2851,
    locationId: 72,
    quantity: 180,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець скальний "Блю Ерроу',
    id: 2895,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець скельний "Сільвер Стар"',
    id: 2853,
    locationId: 72,
    quantity: 57,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець скельний "Сільвер Стар"',
    id: 2886,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець скельний "Скайрокет"',
    id: 2885,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці агрусу Інвікта зелений 2 р.',
    id: 3821,
    locationId: 68,
    quantity: 251,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці агрусу Хіннонмакі Ред 2 р.',
    id: 3824,
    locationId: 68,
    quantity: 269,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії Крупноплідна',
    id: 382455,
    locationId: 69,
    quantity: 14,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії  Загадкова',
    id: 382454,
    locationId: 69,
    quantity: 35,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії Красуня 1 р.',
    id: 3846,
    locationId: 69,
    quantity: 427,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії Оригінальна 1 р.',
    id: 3860,
    locationId: 69,
    quantity: 77,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії Пурпурова 2 р.',
    id: 2989,
    locationId: 69,
    quantity: 5,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії Смарагд 1 р.',
    id: 3847,
    locationId: 69,
    quantity: 170,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії Смарагд 2 р.',
    id: 3870,
    locationId: 69,
    quantity: 5,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці малини Зюгана 1 р.',
    id: 1671,
    locationId: 68,
    quantity: 99,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці малини Аміра Жовта 1 р.',
    id: 2631,
    locationId: 68,
    quantity: 97,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці ожини Блек Сатін 1 р.',
    id: 4348,
    locationId: 69,
    quantity: 6,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці ожини Блек Сатін 1 р.',
    id: 4284,
    locationId: 68,
    quantity: 251,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці ожиномалини Букінгем Тайберрі 1 р.',
    id: 4354,
    locationId: 68,
    quantity: 207,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці ожини Лох Тей 1 р.',
    id: 4355,
    locationId: 68,
    quantity: 224,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці ожини Тризуб 1 р.',
    id: 4355,
    locationId: 68,
    quantity: 134,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці ожини Оучіта 1 р.',
    id: 43551,
    locationId: 69,
    quantity: 307,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Хеномелес 2 р.',
    id: 4204,
    locationId: 62,
    quantity: 126,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Берклі 3 р.',
    id: 4287,
    locationId: 71,
    quantity: 9,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Блю Голд 1 р.',
    id: 4333,
    locationId: 71,
    quantity: 174,
    pot: '1.5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Блю Голд 2 р.',
    id: 621,
    locationId: 71,
    quantity: 420,
    pot: '1.5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Блю Кроп 2 р.',
    id: 626,
    locationId: 71,
    quantity: 78,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Блю Кроп 3 р.',
    id: 4362,
    locationId: 71,
    quantity: 26,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Блю Кроп 4 р.',
    id: 4289,
    locationId: 71,
    quantity: 30,
    pot: '7L кр',
  },
  {
    name: 'Саджанці чорниці Бонус 2 р.',
    id: 2677,
    locationId: 71,
    quantity: 10,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Бонус 3 р.',
    id: 4363,
    locationId: 71,
    quantity: 9,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Дарроу 1,5 р.',
    id: 4334,
    locationId: 71,
    quantity: 365,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Дарроу 2 р.',
    id: 4206,
    locationId: 71,
    quantity: 82,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Дюк 2 р.',
    id: 4367,
    locationId: 70,
    quantity: 160,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Дюк 3 р.',
    id: 4366,
    locationId: 70,
    quantity: 14,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Еліот 1,5 р.',
    id: 4368,
    locationId: 70,
    quantity: 440,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Еліот 2 р.',
    id: 2905,
    locationId: 70,
    quantity: 14,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Еліот 3 р.',
    id: 4364,
    locationId: 70,
    quantity: 4,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Нельсон 2 р.',
    id: 4316,
    locationId: 71,
    quantity: 32,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Река 4 р.',
    id: 4291,
    locationId: 70,
    quantity: 48,
    pot: '7L кр',
  },
  {
    name: 'Саджанці чорниці Сієра 1,5 р.',
    id: 4335,
    locationId: 71,
    quantity: 300,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Сієра 2 р.',
    id: 4134,
    locationId: 71,
    quantity: 110,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Торо 3 р.',
    id: 4292,
    locationId: 71,
    quantity: 266,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Чандлер 1,5 р.',
    id: 4336,
    locationId: 71,
    quantity: 158,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Чандлер 3 р.',
    id: 3467,
    locationId: 71,
    quantity: 157,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Чандлер 2 р.',
    id: 34671,
    locationId: 71,
    quantity: 346,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Барбарис оттавський  "Суперба" 2 р.',
    id: 3863,
    locationId: 60,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Барбарис тунберга "Корнік" 2 р.',
    id: 3061,
    locationId: 60,
    quantity: 200,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Барбарис тунберга "Сільвер Бьюті" 2 р.',
    id: 30616,
    locationId: 60,
    quantity: 200,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Бересклет Форчуна "Емеральд енд Голд" 1 р.',
    id: 4027,
    locationId: 67,
    quantity: 380,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Буддлея давида "Вайт Профьюжн" 1 р.',
    id: 40271,
    locationId: 62,
    quantity: 215,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Верба цільнолиста "Хакуро Нішикі" 1 р.',
    id: 4012,
    locationId: 60,
    quantity: 200,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Конфетті" 1 р',
    id: 17664,
    locationId: 61,
    quantity: 200,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Полар Бер" 2 р.',
    id: 3327,
    locationId: 61,
    quantity: 7,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці Гортензія волотиста "Тардіва" 1 р.',
    id: 1822,
    locationId: 61,
    quantity: 200,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Гортензія деревовидна "Аннабель" 2 р.',
    id: 1822,
    locationId: 61,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Піраканта Оранж Глоу 1 р.',
    id: 1822,
    locationId: 66,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Піраканта Ред Колумн 2 р.',
    id: 1822,
    locationId: 66,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Спірея японська "Голден Прінцес" 1 р.',
    id: 1822,
    locationId: 67,
    quantity: 200,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці черешні Дачниця 1 р.',
    id: 1822,
    locationId: 59,
    quantity: 100,
    pot: '7.5L кр',
  },
  {
    name: 'Саджанці черешні Китаївська Чорна 1 р.',
    id: 1822,
    locationId: 59,
    quantity: 100,
    pot: '7.5L кр',
  },
  {
    name: 'Саджанці яблуні Вільямс Прайд 2 р.',
    id: 1822,
    locationId: 51,
    quantity: 20,
    pot: '12L кр',
  },
  {
    name: 'Саджанці троянд на штамбі Інгрід Бергман 90',
    id: 1800,
    locationId: 44,
    quantity: 54,
    pot: '7.5L кр',
  },
  {
    name: 'Саджанці троянд на штамбі Містер Лінкольн 90',
    id: 1800,
    locationId: 44,
    quantity: 43,
    pot: '12L кр',
  },
  {
    name: 'Саджанці троянд на штамбі Ред Мейлав 90',
    id: 1800,
    locationId: 44,
    quantity: 6,
    pot: '12L кр',
  },
  {
    name: 'Саджанці Туя західна "Тіні Тім"',
    id: 1800,
    locationId: 75,
    quantity: 100,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ялівець скельний "Скайрокет"',
    id: 1800,
    locationId: 73,
    quantity: 53,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії Віті Ківі 2 р.',
    id: 1800,
    locationId: 79,
    quantity: 108,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці актинідії Запилювач 2 р.',
    id: 1800,
    locationId: 79,
    quantity: 52,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці жимолості Блю Банан 1 р.',
    id: 1800,
    locationId: 69,
    quantity: 295,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці жимолості Бореал Бьюті 1 р.',
    id: 1800,
    locationId: 69,
    quantity: 289,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці жимолості Восторг 1 р.',
    id: 1800,
    locationId: 79,
    quantity: 399,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці Ірги Ламарка 2 р.',
    id: 1800,
    locationId: 78,
    quantity: 191,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці суниці садової Румба (5 шт)',
    id: 1800,
    locationId: 76,
    quantity: 108,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці суниці садової Аромас (5 шт)',
    id: 1800,
    locationId: 76,
    quantity: 162,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці суниці садової Хоней (5 шт)',
    id: 1800,
    locationId: 76,
    quantity: 108,
    pot: '3L кв-кр',
  },
  {
    name: 'Саджанці чорниці Блю Голд 3 р.',
    id: 1800,
    locationId: 71,
    quantity: 40,
    pot: '5L кв-кр',
  },
  {
    name: 'Саджанці чорниці Блю Кроп 1 р.',
    id: 1800,
    locationId: 79,
    quantity: 375,
    pot: '1.5L кв',
  },
  {
    name: 'Саджанці чорниці Бонус 1 р.',
    id: 1800,
    locationId: 79,
    quantity: 112,
    pot: '1.5L кв',
  },
  {
    name: 'Саджанці чорниці Еліот 1 р.',
    id: 1800,
    locationId: 79,
    quantity: 279,
    pot: '1.5L кв',
  },
  {
    name: 'Саджанці чорниці Еліот 4 р.',
    id: 1800,
    locationId: 70,
    quantity: 36,
    pot: '7L кр',
  },
  {
    name: 'Саджанці чорниці Патріот 1 р.',
    id: 1800,
    locationId: 79,
    quantity: 122,
    pot: '1.5L кв',
  },
];

export default sku;
